server:
  port: 9000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: trace
    org.springframework.security.jackson2: INFO
    com.celi.spring.authorizationserver.config : DEBUG
